services:
  dns:
    image: strm/dnsmasq
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "5363:53/tcp"
      - "5363:53/udp"
    cap_add:
      - NET_ADMIN
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./caddy.json:/etc/caddy/caddy.json
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/caddy.json", "--resume"]

volumes:
  caddy_data:
  caddy_config: