services:
  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
  caddy:
    restart: always
    image: caddy:latest
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./config/sites:/etc/caddy/sites
      - ./ssl:/etc/ssl:ro
      - ./public:/public
    networks:
      internal:
        aliases:
          - acme.localhost